### ISSUE TITLE
PersistentDictionary - Incompatible with NET 4.5

### ISSUE THREAD

**Issue by Nehmiabm** [microsoft/ManagedEsent#18]
Hello,

I'm not able to build my .NET 4.5 project since the ManagedEsent libraries are compiled against 4.6.2. How can I make this work?

The primary reference "Esent.Collections, Version=1.9.4.1, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Esent.Isam, Version=1.9.4.1, Culture=neutral, PublicKeyToken=null" which was built against the ".NETFramework,Version=v4.6.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".	FileParserPOC

**Comment by machish** [comment]
@Nehmiabm , is it actually 4.5 you're talking about, or 4.5.2?
https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework says that 4.5 and 4.5.1 are end-of-life, but 4.5.2 is still supported.
Is there a good reason that you don't want to upgrade to a newer version of the framework?
cc: @michaelthorp

**Comment by Nehmiabm** [comment]
@machish The company project I'm working on are using 4.5.2 and not upgrading to latest farmework any time soon.
I downloaded the source code and compiled it against 4.5.2 and it worked for me.
Thank you for checking on me :)
