### ISSUE TITLE
New NuGet Package for v.1.9.5

### ISSUE THREAD

**Issue by DanielEggers** [microsoft/ManagedEsent#25]
On [Nuget](https://www.nuget.org/packages/ManagedEsent/) there is still only the old version 1.9.4 available.
Can you please add a package for v.1.9.5 and include the Esent.Collections.dll.
By the way the version number or the [DLLs](https://github.com/Microsoft/ManagedEsent/releases/tag/v1.9.5) is 1.9.4.1 and not 1.9.5, why?
Maybe you could make use of multi-targeting by adding a ".NET Standard 2.0" target to nuget.

However what is really needed is a .NET Core 3.0 compatible version. 
It is not that easy as System.RuntimeType is not [serializable](https://github.com/dotnet/corefx/issues/23213) and therefore the BinaryFormatter in Api.SerializeObjectToColumn in Microsoft.Isam.Esent.Interop fails. The issue #9 was closed without a reason.

**Comment by machish** [comment]
Hi @michaelthorp , are there any plans to push out a `1.9.5` binary on nuget.org?

**Comment by davideforgione** [comment]
Any news on this?

**Comment by michaelthorp** [comment]
I'm not actually sure how 1.9.5 got posted without the Nuget package, but an update is pending (just waiting on approval) with some bug fixes and also moves everything to .NET Standard 2.0, which should be a welcome change.

**Comment by MatthewSteeples** [comment]
I can see that v2 is now on NuGet, but there doesn't seem to be a an update to the [Collections package](https://www.nuget.org/packages/Microsoft.Database.Collections.Generic/). Is that planned too?

**Comment by michaelthorp** [comment]
Yes, it should be ready early next week. There were some compliance issues with the metadata (new guidelines on marking packages as Microsoft-owned) that I'm working on. Apologies for the delay. The full set of assemblies is available on the release section of our GitHub repo page if you want to get started on testing before the Nuget gets released.

**Comment by michaelthorp** [comment]
Ok, the two remaining packages are available now. I will also be re-releasing the ManagedEsent package and will unfortunately have to make it a new package. Microsoft is requiring all Microsoft-sourced packages to be named Microsoft.<something> so this is a required rename.

**Comment by michaelthorp** [comment]
Ok, last update on this issue:

Nuget has all 2.0.0 packages listed properly. Please note that ManagedEsent was renamed to Microsoft.Database.ManagedEsent and re-released as a new package. Please move to the new package when possible as all updates in the future will only be able to be released to that package.
