### ISSUE TITLE
Nuget package Esent.Collections.dll missing since v1.9.0.1

### ISSUE THREAD

**Issue by davideforgione** [microsoft/ManagedEsent#32]
Hi,

i see that since v1.9.0.1 Esent.Collections.dll is not included anymore in the nuget package. 
How's this? There's another package to include or it's just missing?

I'm using PersistentDictionaries so i need to reference collections too.

**Comment by michaelthorp** [comment]
There are three Nuget packages - ManagedEsent, Microsoft.Database.Collections.Generic, and Microsoft.Database.Isam. Please note that they are getting updated to 2.0.0 right now.
