### ISSUE TITLE
Not able to use "using namespace Microsoft::Isam::Esent::Interop" in C++

### ISSUE THREAD

**Issue by skanyal31** [microsoft/ManagedEsent#54]
I'm trying to use this as an example https://github.com/microsoft/ManagedEsent/blob/master/Documentation/CppManagedEsentSample.md but Visual studio can't find **Microsoft::Isam::Esent::Interop**. I have made my project as CLR with .net target framework v4.7.2. Do i need to install some packages ? Tried searching on google but couldn't find anything.

**Comment by skanyal-rubrik** [comment]
I was able to build the Esent.Interop.dll & place it in `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2`. And then add it to my visual studio project `References`. Once added, the C++ apis could be used in CLR project

**Comment by skanyal31** [comment]
I was able to build the Esent.Interop.dll & place it in `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2`. And then add it to my visual studio project References. Once added, the C++ apis could be used in CLR project
