### ISSUE TITLE
EsentVersion does not support 8.1 or 10 features on Windows 10

### ISSUE THREAD

**Issue by pmlyon** [Microsoft/ManagedEsent#6]
I'm on the Windows 10 FCU, I haven't tried on any other version of Windows.

If I start a blank dotnet solution and add the ManagedEsent 1.9.4 NuGet dependency, I see the following values:

EsentVersion.SupportsVistaFeatures = True
EsentVersion.SupportsWindows8Features = True
EsentVersion.SupportsWindows81Features = False
EsentVersion.SupportsWindows10Features = False

Are the 8.1 and 10 features no longer supported on Windows 10?

```csharp
using Microsoft.Isam.Esent.Interop;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(EsentVersion.SupportsVistaFeatures); // True
            Console.WriteLine(EsentVersion.SupportsWindows8Features); // True
            Console.WriteLine(EsentVersion.SupportsWindows81Features); // False
            Console.WriteLine(EsentVersion.SupportsWindows10Features); // False
            Console.ReadLine();
        }
    }
}
```

App.config
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
    </startup>
</configuration>
```

packages.config
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="ManagedEsent" version="1.9.4" targetFramework="net461" />
</packages>
```

**Comment by machish** [comment]
Try running something like `GetVersionEx`. You'll see that it thinks it's on Windows 8.1, unless you specifically target Windows 10 in your manifest.

https://msdn.microsoft.com/en-us/library/windows/desktop/dn481241(v=vs.85).aspx

I don't like that the App Compat team at MS decided that, but they did, and that's what we have to live with.

**Comment by pmlyon** [comment]
Oops, sorry for the spurious bug! Your solution worked perfectly, thanks!!
